services:
  - type: web
    runtime: node
    name: delivera
    buildCommand: npm install && npm run build:css
    startCommand: npm start
    healthCheckPath: /healthz
    maxShutdownDelaySeconds: 30
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: JIRA_HOST
        sync: false
      - key: JIRA_EMAIL
        sync: false
      - key: JIRA_API_TOKEN
        sync: false
      - key: APP_LOGIN_USER
        sync: false
      - key: APP_LOGIN_PASSWORD
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: DELIVERA_SUPER_ADMIN_USERS
        sync: false
      - key: CACHE_BACKEND
        value: redis
      - key: REDIS_URL
        sync: false
